### ISSUE TITLE
yaml requirement

### ISSUE THREAD

**Issue by ia-davidpichler** [cortexlabs/nucleus#8]
I think PyYaml needs to be in the requirements. This is what I ran into:
```bash
$ conda create -n nucleus python=3.8
$ conda activate nucleus
$ pip install git+https://github.com/cortexlabs/nucleus.git@0.2.0
$ nucleus
Traceback (most recent call last):
  File "/home/davidpichler/miniconda3/envs/nucleus/bin/nucleus", line 5, in <module>
    from nucleus.main import cli
  File "/home/davidpichler/miniconda3/envs/nucleus/lib/python3.8/site-packages/nucleus/main.py", line 16, in <module>
    from nucleus.generate import generate
  File "/home/davidpichler/miniconda3/envs/nucleus/lib/python3.8/site-packages/nucleus/generate.py", line 21, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
$ pip install PyYaml
$ nucleus
Usage: nucleus [OPTIONS] COMMAND [ARGS]...

  Use the Nucleus CLI to generate model servers for Python-generic and
  TensorFlow models. Compatible with Cortex clusters.

Options:
  --help  Show this message and exit.

Commands:
  generate  A utility to generate Dockerfile(s) for Nucleus model servers.
  version   Get Nucleus CLI version.
```

**Comment by deliahu** [comment]
Thanks for letting us know! I've just created a PR for this (#9)
